//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evidence_work.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrySpot
    {
        public int EntrySpotId { get; set; }
        public int ClientId { get; set; }
        public int BookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Client Client { get; set; }
    }
}
